#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'route-planner==0.0.0','console_scripts','npc_with_quest'
__requires__ = 'route-planner==0.0.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('route-planner==0.0.0', 'console_scripts', 'npc_with_quest')()
    )
